modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"


[[mods]] #mandatory
modId="swplanets" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Star Wars Planet" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra"
logoFile="logo.png" #optional
credits="" #optional
authors="TATHAN" #optional
description='''
This Mod is a Addon for Ad Astra!.
It add planets from Star Wars and Light Saber :)
'''
[[dependencies.swplanets]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.swplanets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
