modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TathanDev/StarWarsPlanets-AdAstra/issues"



[[mods]]
modId="swplanets"
version="${file.jarVersion}"
displayName="Star Wars Planet"
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra"
logoFile="logo.png"
credits=""
authors="TATHAN"
description='''
This Mod is an Addon for Ad Astra!.
It add planets from Star Wars and Light Sabers :)
'''
[[dependencies.swplanets]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swplanets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"


