modLoader = "javafml"
loaderVersion= "[2,)"
license = "ARR"
issueTrackerURL="https://github.com/TathanDev/StarWarsPlanets-AdAstra/issues"
[[mods]]

modId = "swplanets"
version = "${version}"
displayName = "Star Wars Planets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/"
logoFile="swplanets.png"
credits="TATHAN"
authors = "TathanDev"
description = '''This Mod is an Addon for Ad Astra!.
It add planets from Star Wars, Light Sabers and more :)
'''
[[mixins]]
config = "swplanets.mixins.json"

[[dependencies.swplanets]]
modId = "neoforge"
type="required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.swplanets]]
modId = "minecraft"
type="required"
versionRange = "1.20.4"
ordering = "NONE"
side = "BOTH"
[[dependencies.swplanets]]
modId = "resourcefullib"
type = "required"
versionRange = "[2.4.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swplanets]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[2.4.2,)"
ordering = "NONE"
side = "BOTH"