modLoader = "javafml"
loaderVersion = "[1,)"
license = "Terrarium License"
issueTrackerURL="https://github.com/TathanDev/StarWarsPlanets-AdAstra/issues"

[[mods]]
modId = "swplanets"
version = "${version}"
displayName = "Star Wars Planets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra/"
logoFile = "icon.png"
authors = "TATHAN"
credits = "TATHAN"
description = '''This Mod is an Addon for Ad Astra!.
It add planets from Star Wars, Light Sabers and more :)
'''
[[mixins]]
config = "swplanets.mixins.json"

[[dependencies.swplanets]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swplanets]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swplanets]]
modId = "resourcefullib"
type="required"
versionRange = "[2.4.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swplanets]]
modId = "resourcefulconfig"
type="required"
versionRange = "[2.4.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.swplanets]]
modId = "botarium"
type="required"
versionRange = "[3.0.7,)"
ordering = "NONE"
side = "BOTH"
